/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labpractico4;

import java.util.HashSet;
import javax.swing.JInternalFrame;

/**
 *
 * @author patri
 */
public class ColegioFrame extends javax.swing.JFrame {
   public static  HashSet<Alumno> vistaAlumnos;
   public  static  HashSet<Materia> vistaMateria;
    /**
     * Creates new form ColegioFrame
     */
    public ColegioFrame() {
        initComponents();
        vistaAlumnos= new HashSet<Alumno>();
        vistaMateria= new HashSet<Materia>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAlumno = new javax.swing.JMenu();
        menuAlumno = new javax.swing.JMenuItem();
        mMateria = new javax.swing.JMenu();
        menuMateria = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        menuInscripcion = new javax.swing.JMenuItem();
        menus = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLEGIO");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);

        mAlumno.setBackground(new java.awt.Color(204, 204, 204));
        mAlumno.setForeground(new java.awt.Color(0, 0, 0));
        mAlumno.setText("Alumno");

        menuAlumno.setBackground(new java.awt.Color(204, 204, 204));
        menuAlumno.setText("Agregar alumno");
        menuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnoActionPerformed(evt);
            }
        });
        mAlumno.add(menuAlumno);

        jMenuBar1.add(mAlumno);

        mMateria.setBackground(new java.awt.Color(204, 204, 204));
        mMateria.setForeground(new java.awt.Color(0, 0, 0));
        mMateria.setText("Materia");

        menuMateria.setText("Agregar Materia");
        menuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateriaActionPerformed(evt);
            }
        });
        mMateria.add(menuMateria);

        jMenuBar1.add(mMateria);

        menuRegistro.setBackground(new java.awt.Color(204, 204, 204));
        menuRegistro.setForeground(new java.awt.Color(0, 0, 0));
        menuRegistro.setText("Registro");

        menuInscripcion.setText("Inscripcion");
        menuInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInscripcionActionPerformed(evt);
            }
        });
        menuRegistro.add(menuInscripcion);

        jMenuBar1.add(menuRegistro);

        menus.setBackground(new java.awt.Color(204, 204, 204));
        menus.setForeground(new java.awt.Color(0, 0, 0));
        menus.setText("Salir");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menus.add(menuSalir);

        jMenuBar1.add(menus);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnoActionPerformed
       VentanaAlumno ventAlumno= new VentanaAlumno();
       escritorio.add(ventAlumno);
       ventAlumno.setVisible(true);
       centrarInternalFrame(ventAlumno);
    }//GEN-LAST:event_menuAlumnoActionPerformed

    private void menuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateriaActionPerformed
        VentanaMateria ventMateria= new VentanaMateria();
        escritorio.add(ventMateria);
        ventMateria.setVisible(true);
        centrarInternalFrame(ventMateria);
    }//GEN-LAST:event_menuMateriaActionPerformed

    private void menuInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInscripcionActionPerformed
        VentanaInscripcion ventIns= new VentanaInscripcion();        
        escritorio.add(ventIns);        
        ventIns.setVisible(true);       
        centrarInternalFrame(ventIns);
    }//GEN-LAST:event_menuInscripcionActionPerformed

    private void centrarInternalFrame(JInternalFrame internalFrame) {
        // Centrar el internal frame en el escritorio
        int x = (escritorio.getWidth() - internalFrame.getWidth()) / 2;
        int y = (escritorio.getHeight() - internalFrame.getHeight()) / 2;
        internalFrame.setLocation(x, y);
    }
    
    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que querés Salir?",
                "Confirmar Salida",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            // Para ocultar la ventana pero dejar el programa corriendo.
            // this.setVisible(false);
            
            //Para cerrar la aplicación completamente:
            //System.exit(0);
            
            //Para liberar recursos y cerrar sólo esta ventana:
            this.dispose();
            
            
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
           Alumno lopez= new Alumno(1001,"Lopez","Martin");
           Alumno martinez= new Alumno (1002,"Martinez","Brenda");
           
           Materia laboratorio= new Materia("Laboratorio 1",100,1 );
           Materia matematicas= new Materia("Matematicas",102,1);
           Materia web= new Materia("Web 2",104,2);
           
           lopez.agregarMateria(matematicas);
           lopez.agregarMateria(laboratorio);
           lopez.agregarMateria(web);
           martinez.agregarMateria(matematicas);
           martinez.agregarMateria(laboratorio);
           martinez.agregarMateria(web);
           martinez.agregarMateria(laboratorio);   
           
           lopez.cantidadMaterias();
           martinez.cantidadMaterias();
           
           try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                   if ("Nimbus".equals(info.getName())) {
                       
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                        }
                   }
               
               } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                   java.util.logging.Logger.getLogger(ColegioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                   }//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColegioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColegioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColegioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColegioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ColegioFrame().setVisible(true);
            }
        });
    }
    public static void agregarMateria(Materia materia) {
        vistaMateria.add(materia);
    }

    public static void agregarAlumno(Alumno alumno) {
        vistaAlumnos.add(alumno);
    }
          
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu mAlumno;
    private javax.swing.JMenu mMateria;
    private javax.swing.JMenuItem menuAlumno;
    private javax.swing.JMenuItem menuInscripcion;
    private javax.swing.JMenuItem menuMateria;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenu menus;
    // End of variables declaration//GEN-END:variables
}
